package com.edgemarket.service;

import com.edgemarket.exception.AlreadyVerifiedException;
import com.edgemarket.exception.DuplicateEmailException;
import com.edgemarket.exception.EmailNotVerifiedException;
import com.edgemarket.exception.InvalidCodeException;
import com.edgemarket.exception.InvalidCredentialsException;
import com.edgemarket.exception.TooManyResendsException;
import com.edgemarket.exception.UserNotFoundException;
import com.edgemarket.model.UserDto;
import io.jsonwebtoken.Jwts;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import javax.crypto.SecretKey;
import java.security.SecureRandom;
import java.time.Instant;
import java.util.Base64;
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.regex.Pattern;

@Service
public class EmailAuthServiceImpl implements EmailAuthService {

    private static final Logger log = LoggerFactory.getLogger(EmailAuthServiceImpl.class);

    private static final Pattern EMAIL_PATTERN =
            Pattern.compile("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$");

    private static final SecureRandom SECURE_RANDOM = new SecureRandom();

    private final JdbcTemplate jdbcTemplate;
    private final SendGridEmailService sendGridEmailService;
    private final EmailRateLimitService emailRateLimitService;
    private final String jwtSecret;

    public EmailAuthServiceImpl(JdbcTemplate jdbcTemplate,
                                SendGridEmailService sendGridEmailService,
                                EmailRateLimitService emailRateLimitService,
                                @Value("${auth.jwt.secret}") String jwtSecret) {
        this.jdbcTemplate = jdbcTemplate;
        this.sendGridEmailService = sendGridEmailService;
        this.emailRateLimitService = emailRateLimitService;
        this.jwtSecret = jwtSecret;
    }

    // -------------------------------------------------------------------------
    // signup
    // -------------------------------------------------------------------------

    @Override
    public void signup(String email, String password) {
        // Validate email
        if (email == null || !EMAIL_PATTERN.matcher(email).matches()) {
            throw new IllegalArgumentException("Valid email is required");
        }

        // Validate password length
        if (password == null || password.length() < 8) {
            throw new IllegalArgumentException("Password must be at least 8 characters");
        }

        // Check for duplicate email
        Integer count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM users WHERE email = ?",
                Integer.class,
                email.toLowerCase());
        if (count != null && count > 0) {
            throw new DuplicateEmailException("Email already registered");
        }

        // Hash password — never log it
        String passwordHash = new BCryptPasswordEncoder(10).encode(password);

        // Insert user (id generated by DB)
        jdbcTemplate.update(
                "INSERT INTO users (id, email, password_hash) VALUES (gen_random_uuid(), ?, ?)",
                email.toLowerCase(),
                passwordHash);

        // Retrieve the newly created user id
        UUID userId = jdbcTemplate.queryForObject(
                "SELECT id FROM users WHERE email = ?",
                UUID.class,
                email.toLowerCase());

        // Generate 6-digit verification code
        String code = String.format("%06d", SECURE_RANDOM.nextInt(1_000_000));

        // Insert verification code (expires in 10 minutes)
        jdbcTemplate.update(
                "INSERT INTO email_verification_codes (id, user_id, code, expires_at) " +
                "VALUES (gen_random_uuid(), ?, ?, NOW() + INTERVAL '10 minutes')",
                userId,
                code);

        // Send code asynchronously — failure is logged inside SendGridEmailService
        sendGridEmailService.sendVerificationCodeAsync(email, code);

        log.info("[EmailAuth] Signup initiated for email={}", email);
    }

    // -------------------------------------------------------------------------
    // verifyEmail
    // -------------------------------------------------------------------------

    @Override
    @Transactional
    public String verifyEmail(String email, String code) {
        // Query most recent unconsumed, unexpired code for this email
        List<Map<String, Object>> rows = jdbcTemplate.queryForList(
                "SELECT u.id, evc.code " +
                "FROM users u " +
                "JOIN email_verification_codes evc ON evc.user_id = u.id " +
                "WHERE u.email = ? " +
                "  AND evc.consumed_at IS NULL " +
                "  AND evc.expires_at > NOW() " +
                "ORDER BY evc.created_at DESC " +
                "LIMIT 1",
                email.toLowerCase());

        if (rows.isEmpty()) {
            throw new InvalidCodeException("Invalid or expired code");
        }

        Map<String, Object> row = rows.get(0);
        String storedCode = (String) row.get("code");

        // Code comparison — always run even if no row, to avoid timing differences
        if (!code.equals(storedCode)) {
            throw new InvalidCodeException("Invalid or expired code");
        }

        UUID userId = (UUID) row.get("id");

        // Mark email verified
        jdbcTemplate.update(
                "UPDATE users SET email_verified = TRUE WHERE id = ?",
                userId);

        // Mark code consumed
        jdbcTemplate.update(
                "UPDATE email_verification_codes SET consumed_at = NOW() " +
                "WHERE user_id = ? AND code = ? AND consumed_at IS NULL",
                userId,
                code);

        log.info("[EmailAuth] Email verified for userId={}", userId);
        return issueJwt(userId);
    }

    // -------------------------------------------------------------------------
    // login
    // -------------------------------------------------------------------------

    @Override
    public String login(String email, String password) {
        // Look up user by email
        Map<String, Object> user;
        try {
            List<Map<String, Object>> rows = jdbcTemplate.queryForList(
                    "SELECT id, password_hash, email_verified FROM users WHERE email = ?",
                    email.toLowerCase());
            if (rows.isEmpty()) {
                throw new InvalidCredentialsException("Invalid credentials");
            }
            user = rows.get(0);
        } catch (EmptyResultDataAccessException e) {
            throw new InvalidCredentialsException("Invalid credentials");
        }

        String passwordHash = (String) user.get("password_hash");

        // Verify password — always check to avoid timing attacks
        BCryptPasswordEncoder encoder = new BCryptPasswordEncoder(10);
        boolean matches = encoder.matches(password, passwordHash);

        if (!matches) {
            throw new InvalidCredentialsException("Invalid credentials");
        }

        // Check email verified
        Boolean emailVerified = (Boolean) user.get("email_verified");
        if (emailVerified == null || !emailVerified) {
            throw new EmailNotVerifiedException();
        }

        UUID userId = (UUID) user.get("id");
        log.info("[EmailAuth] Login successful for userId={}", userId);
        return issueJwt(userId);
    }

    // -------------------------------------------------------------------------
    // resendCode
    // -------------------------------------------------------------------------

    @Override
    public void resendCode(String email) {
        // Check rate limit first
        if (!emailRateLimitService.allow(email)) {
            throw new TooManyResendsException("Too many resend requests. Try again later.");
        }

        // Look up user — return silently if not found to avoid enumeration
        List<Map<String, Object>> rows = jdbcTemplate.queryForList(
                "SELECT id, email_verified FROM users WHERE email = ?",
                email.toLowerCase());

        if (rows.isEmpty()) {
            // No-op: do not reveal whether the email exists
            return;
        }

        Map<String, Object> user = rows.get(0);
        Boolean emailVerified = (Boolean) user.get("email_verified");

        if (emailVerified != null && emailVerified) {
            throw new AlreadyVerifiedException("Email already verified");
        }

        UUID userId = (UUID) user.get("id");

        // Invalidate all existing unconsumed codes
        jdbcTemplate.update(
                "UPDATE email_verification_codes SET consumed_at = NOW() " +
                "WHERE user_id = ? AND consumed_at IS NULL",
                userId);

        // Generate and store new code
        String code = String.format("%06d", SECURE_RANDOM.nextInt(1_000_000));

        jdbcTemplate.update(
                "INSERT INTO email_verification_codes (id, user_id, code, expires_at) " +
                "VALUES (gen_random_uuid(), ?, ?, NOW() + INTERVAL '10 minutes')",
                userId,
                code);

        // Send asynchronously
        sendGridEmailService.sendVerificationCodeAsync(email, code);

        log.info("[EmailAuth] Verification code resent for userId={}", userId);
    }

    // -------------------------------------------------------------------------
    // getUser
    // -------------------------------------------------------------------------

    @Override
    public UserDto getUser(UUID userId) {
        List<Map<String, Object>> rows = jdbcTemplate.queryForList(
                "SELECT id, email, email_verified, wallet_address FROM users WHERE id = ?::uuid",
                userId.toString());

        if (rows.isEmpty()) {
            throw new UserNotFoundException("User not found: " + userId);
        }

        Map<String, Object> row = rows.get(0);
        return new UserDto(
                (UUID) row.get("id"),
                (String) row.get("email"),
                Boolean.TRUE.equals(row.get("email_verified")),
                (String) row.get("wallet_address"));
    }

    // -------------------------------------------------------------------------
    // JWT helper
    // -------------------------------------------------------------------------

    private String issueJwt(UUID userId) {
        Instant now = Instant.now();
        SecretKey secretKey = io.jsonwebtoken.security.Keys.hmacShaKeyFor(
                Base64.getDecoder().decode(jwtSecret));

        return Jwts.builder()
                .subject(userId.toString())
                .issuedAt(Date.from(now))
                .expiration(Date.from(now.plusSeconds(86400)))
                .signWith(secretKey)
                .compact();
    }
}
